language: bash
sudo: false
addons:
  apt:
    packages:
    - git
    - build-essential
    - texlive-full
    - pandoc
script: make -s install
env:
  global:
    secure: hB7ob3qS0zTkCklMiHMi6VcNi97ijCdV2fPxgyTx6MLCKhLrrKmEwtT8b+gNkThD1kVuu97adCBYjr5tVgNkl9SExeWQG4LMizrihK6WnHAAkfJipxVJzNeuIOcdBcTPhNjSQ67NdCVjneOXQ6vbwljHG1GHPCtTTH6hxk60QDQ=
