all: pdf html epub latex

pdf:
	markdown2pdf README.md -o damianzaremba-long.pdf

html:
	pandoc README.md -o damianzaremba-long.html

epub:
	pandoc README.md -o damianzaremba-long.epub

latex:
	pandoc README.md -o damianzaremba-long.tex
