name: Continuous Deployment
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install system dependancies
        run: sudo apt-get install -y make pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Transpile formats
        run: make all

      - name: Publish the new entries to branch
        run: |
          git add --all && (
            git config --global user.name "InfraBits CI"
            git config --global user.email "ci@infrabits.nl"

            git commit -m "Auto publishing formats"
            git push origin ${GITHUB_REF#refs/heads/}
          ) || true
